# Generated by Django 4.2.3 on 2023-07-28 13:08
from django.db import migrations
from django.db.migrations import RunPython
from django.core.management import call_command
from django.contrib.auth.hashers import make_password

FIXTURES = ['location', 'user']


def load_fixtures(apps, schema_editor):
    # Load data from fixtures
    for fixture in FIXTURES:
        call_command('loaddata', fixture, app_label='users')

    # Set correctly hashed passwords
    User = apps.get_model('users', 'User')
    for user in User.objects.all():
        user.password = make_password(user.password)
        user.save()


def remove_fixture_data(apps, schema_editor):
    """
    Reverse function
    """
    User = apps.get_model('users', 'User')
    Location = apps.get_model('users', 'User')

    User.objects.all().delete()
    Location.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_age_user_birth_date_alter_user_email'),
    ]

    operations = [
        RunPython(load_fixtures, reverse_code=remove_fixture_data),
    ]
