# Generated by Django 4.2.3 on 2023-07-28 13:23

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_reload_intial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[users.validators.NotOnDomainValidator('rambler.ru')]),
        ),
    ]
