# Generated by Django 4.2.3 on 2023-07-04 11:25
from typing import Generator

from django.db import migrations

import csv


def read_csv(filename: str) -> Generator[dict, None, None]:
    with open(filename, encoding='utf-8') as f:
        for row in csv.DictReader(f):
            yield row


def load_ads(apps, schema_editor):
    Ad = apps.get_model('ads', 'Ad')

    ads_data = read_csv('ads.csv')
    for ad in ads_data:
        new_ad = Ad()

        new_ad.id = ad['Id']
        new_ad.name = ad['name']
        new_ad.author = ad['author']
        new_ad.price = ad['price']
        new_ad.description = ad['description']
        new_ad.address = ad['address']
        new_ad.is_published = True if ad['is_published'] == 'TRUE' else False

        new_ad.save()


def load_categories(apps, schema_editor):
    Category = apps.get_model('ads', 'Category')

    category_data = read_csv('categories.csv')

    for category in category_data:
        new_category = Category()

        new_category.id = category['id']
        new_category.name = category['name']

        new_category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_ads),
        migrations.RunPython(load_categories),
    ]
