# Generated by Django 4.2.3 on 2023-07-24 13:03

from django.db import migrations
from django.core.management import call_command
from django.db.migrations import RunPython

FIXTURES = ['category', 'ad']


def load_fixtures(apps, schema_editor):
    for fixture in FIXTURES:
        call_command('loaddata', fixture, app_label='ads')


def remove_fixture_data(apps, schema_editor):
    """
    Reverse function
    """
    Ad = apps.get_model('ads', 'Ad')
    Category = apps.get_model('ads', 'Category')

    Ad.objects.all().delete()
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_initial'),
        ('users', '0002_load_intial_data'),
    ]

    operations = [
        RunPython(load_fixtures, reverse_code=remove_fixture_data)
    ]
