# Generated by Django 4.2.3 on 2023-07-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_adselection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adselection',
            options={'verbose_name': 'Подборка', 'verbose_name_plural': 'Подборки'},
        ),
    ]
