# Generated by Django 4.2.3 on 2023-07-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_remove_ad_address_alter_ad_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location_id',
            new_name='location',
        ),
    ]
