# Generated by Django 4.2.3 on 2023-07-17 13:33

import csv
from django.db import migrations
from typing import Generator


def read_csv(filename: str) -> Generator[dict, None, None]:
    with open(filename, encoding='utf-8') as f:
        for row in csv.DictReader(f):
            yield row


def load_categories(apps, schema_editor):
    Category = apps.get_model('ads', 'Category')

    category_data = read_csv('category.csv')

    for category in category_data:
        new_category = Category()

        new_category.id = category['id']
        new_category.name = category['name']

        new_category.save()


def load_locations(apps, schema_editor):
    Location = apps.get_model('ads', 'Location')

    location_data = read_csv('location.csv')

    for location in location_data:
        new_location = Location()

        new_location.id = location['id']
        new_location.name = location['name']
        new_location.lat = location['lat']
        new_location.lng = location['lng']

        new_location.save()


def load_users(apps, schema_editor):
    User = apps.get_model('ads', 'User')

    user_data = read_csv('user.csv')

    for user in user_data:
        new_user = User()

        new_user.id = user['id']
        new_user.username = user['username']
        new_user.first_name = user['first_name']
        new_user.last_name = user['last_name']
        new_user.password = user['password']
        new_user.role = user['role']
        new_user.age = int(user['age'])
        new_user.location_id = int(user['location_id'])

        new_user.save()


def load_ads(apps, schema_editor):
    Ad = apps.get_model('ads', 'Ad')

    ads_data = read_csv('ad.csv')
    for ad in ads_data:
        new_ad = Ad()

        new_ad.id = ad['Id']
        new_ad.name = ad['name']
        new_ad.author_id = ad['author_id']
        new_ad.price = ad['price']
        new_ad.description = ad['description']
        new_ad.is_published = True if ad['is_published'] == 'TRUE' else False
        new_ad.image = ad['image']
        new_ad.category_id = ad['category_id']

        new_ad.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_rename_location_id_user_location'),
    ]

    operations = [
        migrations.RunPython(load_categories),
        migrations.RunPython(load_locations),
        migrations.RunPython(load_users),
        migrations.RunPython(load_ads),
    ]
