# Generated by Django 4.2.3 on 2023-07-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_remove_user_location_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
    ]
