# Generated by Django 4.2.3 on 2023-07-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_alter_location_lat_alter_location_lng'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
